In [1]:
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# === CELL TYPE: IMPORTS AND SETUP 

# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# === CELL TYPE: IMPORTS AND SETUP 

import os                       # for testing use only
import requests
import numpy as np
import pandas as pd
import sklearn
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from os import path
from sklearn.model_selection import train_test_split
# --------cross-validation
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
# -------- classification
from sklearn import neighbors, tree, ensemble, naive_bayes, svm
# *** KNN
from sklearn.neighbors import KNeighborsClassifier
# *** Decision Tree; Random Forest
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
# *** Naive Bayes
from sklearn.naive_bayes import GaussianNB
# *** SVM classifier
from sklearn.svm import SVC
# --------  metrics:
from sklearn import metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, r2_score, confusion_matrix
from sklearn.metrics import make_scorer
from bs4 import BeautifulSoup
from collections import Counter
from sklearn import linear_model, metrics, preprocessing
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression, LinearRegression
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium import webdriver




%matplotlib inline

In [2]:


fileName='data\YearsCityPop.csv'
if os.path.isfile(fileName):
    df = pd.read_csv(fileName)
    df.sort_values(by="year",ascending=False)
    df
else:
    PATH = "C:/Users/shake/chromedriver.exe"
    url="https://boardsgenerator.cbs.gov.il/pages/WebParts/YishuvimPage.aspx?level_1=%D7%A9%D7%9B%D7%A8%20/%20%D7%94%D7%9B%D7%A0%D7%A1%D7%95%D7%AA"
    driver = webdriver.Chrome(PATH)
    data=[]
    data=GetYearsCityPop()
    if data:#data not empty    
        df = pd.DataFrame(data, columns=['year','city','population']) 
        df.sort_values(by="year",ascending=False)
        df.to_excel(fileName)
    
print(df)

def GetYearsCityPop():
    data = []    
    PATH = "C:/Users/shake/chromedriver.exe"
    driver = webdriver.Chrome(PATH)
    try:
        driver.get(url)
        driver.implicitly_wait(20)
        driver.maximize_window()
        selectCity = driver.find_element(By.ID, "select2-chosen-8")
        selectCity.click()
        options = driver.find_element(By.XPATH, "//*[@id=\"select2-results-8\"]")
        AllOpt = options.find_elements_by_css_selector("li")
        driver.refresh()
        countOpt=len(AllOpt)
        for i in range(1, countOpt):
            time.sleep(1)
            selectCity = driver.find_element(By.ID, "select2-chosen-8")
            selectCity.click()
            time.sleep(1)
            year = selectCity.text
            driver.find_element(By.XPATH, "//*[@id=\"select2-results-8\"]/li[" + str(i) + "]").click()


            pages = driver.find_element_by_css_selector("div.pager")
            pagesLinkes=pages.find_elements_by_class_name("ng-binding")
            for page in pagesLinkes:
                page.click()
                time.sleep(1)
                tbody = driver.find_element_by_css_selector("tbody")
                tr = tbody.find_elements_by_css_selector("tr")
                for row in tr:
                    td = row.find_elements_by_css_selector("td")
                    cityName = td[1].text
                    poplation = td[7].text
                    poplationNew=poplation.replace(',','')                   
                    data.append([year, cityName, poplationNew])

    except BaseException as e:
        print("Invalid URL")
    

    driver.quit()
    return data

      Unnamed: 0  year                 city population
0              1  2020              אבו גוש       7769
1              2  2020             אבו סנאן      14307
2              3  2020  אבו קורינאת (יישוב)       1994
3              4  2020             אבו תלול       2139
4              5  2020                אבטין       2887
...          ...   ...                  ...        ...
4995        4996  1997        בן שמן (מושב)          -
4996        4997  1997       בן שמן (שיכון)          -
4997        4998  1997              בני ברק          -
4998        4999  1997             בני דרום          -
4999        5000  1997             בני דרור          -

[5000 rows x 4 columns]

In [3]:
# from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium import webdriver
import os                       
import requests
import numpy as np
import pandas as pd


def get_tables():
    timeout = 10
    driver.execute_script("""
    document.querySelectorAll("a[aria-hidden=true],span[aria-hidden=true]").forEach(function(e) {
        e.parentElement.removeChild(e);
    });
    """)
    temp_html = driver.find_element(By.CSS_SELECTOR, "html").get_attribute('outerHTML')
    dfYear = pd.read_html(temp_html, attrs = {'class':'zebraTable ng-scope'})[0]
    return dfYear

def GetYearsDemography(fileName,url):
    try:
        driver.get(url)
        driver.implicitly_wait(20)
        driver.maximize_window()
        selectSubtext = driver.find_element(By.ID, "select2-chosen-4")
        selectSubtext.click()
        driver.find_element(By.XPATH, "//*[@id=\"select2-results-4\"]/li[" + "7" + "]").click()
        time.sleep(10)
        selectCity = driver.find_element(By.ID, "select2-chosen-8")
        selectCity.click()
        time.sleep(1)
        options = driver.find_element(By.XPATH, "//*[@id=\"select2-results-8\"]")
        AllOpt = options.find_elements_by_css_selector("li")

        countOpt=len(AllOpt)
        driver.find_element(By.XPATH, "//*[@id=\"select2-results-8\"]/li[" + "1" + "]").click()

        dfData = pd.DataFrame()
        firstTime = True
        for i in range(1, countOpt):

            driver.find_element(By.ID, "select2-chosen-4").click()
            driver.find_element(By.XPATH, "//*[@id=\"select2-results-4\"]/li[" + "7" + "]").click()
            selectCity = driver.find_element(By.ID, "select2-chosen-8")
            selectCity.click()
            driver.find_element(By.XPATH, "//*[@id=\"select2-results-8\"]/li[" + str(i) + "]").click()
            year = selectCity.text
            temp = get_tables()
            temp.insert(0, "Years", year, True)
            print(temp)
            dfData = dfData.append(temp, ignore_index=True)
            if firstTime:
                temp.to_csv(fileName, mode='a', encoding='utf-8-sig',index=False)
                firstTime = False
            else:
                temp.to_csv(fileName, mode='a', encoding='utf-8-sig',index=False, header=False)


    except BaseException as e:
        print("Invalid URL")
    driver.quit()
    return dfData

In [4]:

from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium import webdriver
import os                       
import requests
import numpy as np
import pandas as pd


fileName='data\YearsDemography.csv'
if os.path.isfile(fileName):
    dfDemography = pd.read_csv(fileName)
else:
    PATH = "C:\Program Files (x86)\chromedriver.exe"
    url="https://boardsgenerator.cbs.gov.il/pages/WebParts/YishuvimPage.aspx?level_1=%D7%A9%D7%9B%D7%A8%20/%20%D7%94%D7%9B%D7%A0%D7%A1%D7%95%D7%AA"
    driver = webdriver.Chrome(PATH)
    dfDemography = GetYearsDemography(fileName)
    
    
dfDemography

,Years,שם יישוב,סמל היישוב,"צפיפות אוכלוסייה לקמ''ר ביישובים שמנו 5,000 תושבים ויותר","סה""כ אוכלוסייה בסוף השנה",יהודים ואחרים (אחוזים),יהודים (אחוזים מתוך יהודים ואחרים),ערבים (אחוזים),מוסלמים (אחוזים מתוך האוכלוסייה הערבית),נוצרים (אחוזים מתוך האוכלוסייה הערבית),...,"נישאים שיעור ל-1,000 תושבים לא נשואים בני 15 ומעלה 2019","מתגרשים סה""כ גברים ונשים 2019","מתגרשים שיעור ל-1,000 תושבים נשואים בני 15 ומעלה 2019",אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) סך מוסדות דיור משותף ברשות,אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) סך דיירי דיור משותף ברשות,אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) אחוז דיירים בבתי אבות ובדיור מוגן,אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) אחוז דיירים במוסדות חינוך,אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) אחוז דיירים במוסדות דת,אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) אחוז דיירים במוסדות אשפוז כולל הוסטלים,אוכלוסיית דיור משותף (אחוז מתוך אוכלוסיית הרשות) אחוז דיירים במוסדות אחרים
0,2020,אבו גוש,472,4114.4,7771.0,-,-,98.9,99.8,-,...,44.6,26,8.1,4,31,-,0.3,0.04,0.06,-
1,2020,אבו סנאן,473,2136.9,14306.0,-,-,99.8,54.6,15.2,...,42.2,29,4.7,-,-,-,-,-,-,-
2,2020,אבן יהודה,182,1696.2,14020.0,100,98.4,-,-,-,...,20,40,7,5,347,1.35,0.3,-,0.83,-
3,2020,אום אל-פחם,2710,2187.4,56777.0,-,-,99.9,100,-,...,53.7,104,4.5,..,..,..,..,..,..,..
4,2020,אופקים,31,1990.8,32555.0,99.3,93.4,-,-,-,...,44.5,119,10.7,6,559,0.87,0.58,0.17,-,0.09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3592,2003,שעב,538,2.9,2.8,14.04,13.56,13.17,9.43,17.07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3593,2003,שפרעם,8800,15.7,15.5,13.2,12.5,10.9,8.33,16.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3594,2003,תל אביב -יפו,5000,173.8,189.6,7,5.5,4.8,5.2,18.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3595,2003,תל מונד,154,4,3.9,11.43,10.62,9.73,7.77,12.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3596,2003,תל שבע,1054,5.9,6.0,24.35,17.33,14.33,10.57,16.44,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [130]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium import webdriver
import os                       
import requests
import numpy as np
import pandas as pd
import time



def GetCollageAndUnivercityNamesAndAddress(UnivercityFileName,CollageFileName):
    dfUniversity = pd.DataFrame(columns=['Name','Address'])
    dfCollege = pd.DataFrame(columns=['Name','Address'])
    dictionaryAcademicType = {'University': '', 'College': ''}
    link_Universities=r"https://che.org.il/המוסדות-להשכלה-גבוהה/#section-79442"
    link_College1=r"https://che.org.il/המוסדות-להשכלה-גבוהה/#section-79446"
    link_College2=r"https://che.org.il/המוסדות-להשכלה-גבוהה/#section-79448"
    link_College3=r"https://che.org.il/המוסדות-להשכלה-גבוהה/#section-79452"
    links = [link_Universities, link_College1, link_College2, link_College3]

   
    try:
        for item in links:      
            driver.get(item)       
            driver.implicitly_wait(20)
            sectionName=item.split("#")
            link = driver.find_element(by=By.ID, value=sectionName[1])
            title=link.find_element_by_css_selector("div.title").text
            subLink=link.find_element_by_css_selector("div.content")
            subsublink=subLink.find_elements_by_css_selector("a")
            print(title)
            linkes = list()
            if str(title) == "אוניברסיטאות":
                for itemLink in subsublink:
                    linkes.append(itemLink.get_attribute("href"))
                dictionaryAcademicType['University'] = linkes
            else:
                for itemLink in subsublink:
                    linkes.append(itemLink.get_attribute("href"))
                dictionaryAcademicType['College'] = linkes

        for itemAcademicType in dictionaryAcademicType:
            typeName = str(itemAcademicType)
            linkStringList = dictionaryAcademicType[itemAcademicType]
            for itemLink in linkStringList:
                try:
                    driver.get(itemLink)
                    driver.implicitly_wait(20)
                    name = driver.find_elements_by_class_name("yellow-title")
                    address = driver.find_elements_by_class_name("col-xs-9")
                   

                    if typeName == "University":
                        dfUniversity = dfUniversity.append({'Name':  name[0].text, 'Address': address[0].text}, ignore_index=True)
                        print(dfUniversity)
                    else:
                        dfCollege = dfCollege.append({'Name': name[0].text, 'Address': address[0].text},ignore_index=True)
                        print(dfCollege)
                    time.sleep(0.5)
                except:
                    print("Invalid URL")
    except:
        print("Invalid URL")
    driver.quit()  
    dfUniversity.to_csv(UnivercityFileName, mode='a', encoding='utf-8-sig', index=False)
    dfCollege.to_csv(CollageFileName, mode='a', encoding='utf-8-sig', index=False)
    return dfUniversity , dfCollege

Out

In [151]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium import webdriver
import os                       
import requests
import numpy as np
import pandas as pd


dfUniversities = pd.DataFrame(columns=['Name','Address'])
dfColleges = pd.DataFrame(columns=['Name','Address'])

UnivercityFileName=r"data\UniversityNamesAndAddress.csv"
CollageFileName=r"data\CollegeNamesAndAddress.csv"


if path.exists(UnivercityFileName and CollageFileName):
    dfUniversities = pd.read_csv(UnivercityFileName)
    dfColleges = pd.read_csv(CollageFileName)
else:
    PATH = "C:\Program Files (x86)\chromedriver.exe"
    driver = webdriver.Chrome(PATH)
    print("Invalid URL")
    dfUniversities,dfColleges = GetCollageAndUnivercityNamesAndAddress(UnivercityFileName,CollageFileName)
    
    
dfUniversities
dfColleges

,Name,Address
0,אלקאסמי – מכללה אקדמית לחינוך,ת.ד. 124 באקה אל גרבייה 30100
1,אמונה-אפרתה – מכללה אקדמית לאמנויות וחינוך,"רח' בן יפונה 17 ת.ד. 10263, ירושלים 91102"
2,המכללה האקדמית בית-ברל,"דואר בית-ברל, 44905"
3,המכללה האקדמית הדתית לחינוך שאנן,רח' הים התיכון 7 (פניית דב פרומר) ת.ד. 906 קרי...
4,המכללה האקדמית הערבית לחינוך בישראל – חיפה,"ת.ד. 8349, רח' החשמל 22, חיפה 33145"
5,המכללה האקדמית בוינגייט,"דואר וינגייט, נתניה 42902"
6,המכללה האקדמית לחינוך גבעת וושינגטון,"ד.נ. אבטח, מיקוד 7923900"
7,המכללה האקדמית לחינוך ולספורט אוהלו בקצרין,"קצרין, ת.ד. 222 מיקוד 12900"
8,"המכללה האקדמית לחינוך ע""ש דוד ילין","ת.ד. 3578, בית הכרם, ירושלים 91035"
9,"המכללה האקדמית לחינוך ע""ש קיי","רח' עזריאל ניצני 6 ת.ד. 4301, באר-שבע 84536"
10,"המכללה האקדמית לחינוך ע""ש א. ד. גורדון","טשרניחובסקי 73, חיפה."
11,"המרכז האקדמי לעיצוב ולחינוך ויצו – חיפה ע""ש נר...","הגנים 21, ת.ד. 9034, חיפה 31090"
12,המכללה האקדמית חמדת,ת. ד. 412 קריית החינוך עזתה נתיבות 80200
13,מכללה אקדמית לחינוך – אורות ישראל מיסודן של מכ...,"קמפוס אלקנה, ד.נ. הרי אפרים 44814"
14,"מכללה אקדמית לחינוך ""אורנים""",דואר קרית טבעון 36006
15,מכללה ירושלים,"ת.ד. 16078, בית וגן ירושלים 91160"
16,המכללה האקדמית הרצוג מיסודן של מכללות ליפשיץ ו...,"אלון שבות, גוש עציון 9043300"
17,המרכז האקדמי לוינסקי-וינגייט,"שושנה פרסיץ 15, קריית החינוך תל-אביב"
18,מכללת סכנין להכשרת עובדי הוראה,"ת.ד. 100, סכנין 20173"
19,סמינר הקיבוצים – המכללה לחינוך לטכנולוגיה ולאו...,"דרך נמיר 149, תל-אביב 62507"
20,תלפיות – המכללה האקדמית לחינוך,"רח' יוטבתה 7, חולון 58114"

In [220]:
# CityNames=pd.DataFrame
#CityNames=dfDemography.loc[dfDemography["Years"] == '2022', 'שם יישוב']
#CityNames=dfDemography[dfDemography['Years']==2020]['שם יישוב']
import numpy as  np

CityNames=dfDemography.query('Years==2020')['שם יישוב']
CityNames

for name in CityNames:
    print(name)
    if dfColleges['Address'].str.contains(name).any():
        print (name + "1")
    #else:
         #print ("is not there")

# if ' 124 באקה אל גרבייה 30100' in dfColleges.values :
#     print("\nThis value exists in Dataframe")
# else :
#     print("\nThis value does not exists in Dataframe")    

# print(dfColleges.values)

אבו גוש
אבו סנאן
אבן יהודה
אום אל-פחם
אופקים
אור יהודה
אור עקיבא
אורנית
אזור
אילת
אכסאל
אליכין
אלעד
אלפי מנשה
אלקנה
אלקנה1
אעבלין
אפרת
אריאל
אשדוד
אשקלון
באקה אל-גרביה
באר יעקב
באר שבע
בועיינה-נוג'ידאת
בוקעאתא
ביר אל-מכסור
בית אל
בית אריה-עופרים
בית ג'ן
בית דגן
בית שאן
בית שמש
ביתר עילית
בני ברק
בני עי"ש
בנימינה-גבעת עדה*
בסמ"ה
בסמת טבעון
בענה
בת ים
גבעת זאב
גבעת שמואל
גבעתיים
ג'דיידה-מכר
גדרה
ג'ולס
ג'לג'וליה
גן יבנה
גני תקווה
ג'סר א-זרקא
ג'ש (גוש חלב)
ג'ת
דאלית אל-כרמל
דבורייה
דייר אל-אסד
דייר חנא
דימונה
הוד השרון
הר אדר
הרצלייה
זכרון יעקב
זמר
זרזיר
חדרה
חולון
חולון1
חורה
חורפיש
חיפה
חיפה1
חצור הגלילית
חריש
טבריה
טובא-זנגרייה
טורעאן
טייבה
טירה
טירת כרמל
טמרה
יאנוח-ג'ת
יבנאל
יבנה
יהוד-מונוסון
יסוד המעלה
יפיע
יקנעם עילית
ירוחם
ירושלים
ירושלים1
ירכא
כאבול
כאוכב אבו אל-היג'א
כוכב יאיר
כסיפה
כסרא-סמיע
כעביה-טבאש-חג'אג'רה
כפר ברא
כפר ורדים
כפר יאסיף
כפר יונה
כפר כמא
כפר כנא
כפר מנדא
כפר סבא
כפר קאסם
כפר קרע
כפר שמריהו
כפר תבור
כרמיאל
להבים
לוד
לקיה
מבשרת ציון
מגאר
מג'ד אל-כרום
מגדל
מגדל העמק
מג'דל שמס
מודיעין עילית
מודיעין-מכבים-רעות*
מזכרת בתיה
מזרעה
מטולה
מיתר
מסעדה
מעיליא
מעלה אדומים
מעלה אפרים
מעלה עירון
מעלות-תרשיחא
מצפה רמון
משהד
נהרייה
נוף הגליל
נחף
נס ציונה
נצרת
נשר
נתיבות
נתיבות1
נתניה
נתניה1
סאג'ור
סביון*
סח'נין
ע'ג'ר
עומר
עיילבון
עילוט
עין מאהל
עין קנייא
עכו
עמנואל
עספיא
עפולה
עראבה
ערד
ערערה
ערערה-בנגב
פוריידיס
פסוטה
פקיעין (בוקייעה)
פרדס חנה-כרכור
פרדסייה
פתח תקווה
צפת
קדומים
קדימה-צורן
קלנסווה
קצרין
קצרין1
קריית אונו
קריית ארבע
קריית אתא
קריית ביאליק
קריית גת
קריית טבעון
קריית ים
קריית יערים
קריית מוצקין
קריית מלאכי
קריית עקרון
קריית שמונה
קרני שומרון
ראמה
ראש העין
ראש פינה
ראשון לציון
רהט
רחובות
ריינה
רכסים
רמלה
רמת גן
רמת השרון
רמת ישי
רעננה
שבלי - אום אל-גנם
שגב-שלום
שדרות
שוהם
שלומי
שעב
שפרעם
תל אביב -יפו
תל מונד
תל שבע

C:\Users\vexxn\AppData\Local\Temp/ipykernel_19216/3795043166.py:10: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  if dfColleges['Address'].str.contains(name).any():